name: CI Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: CI Check Passed
        run: echo "Code is ready to be merged!"
